# Generated by Django 3.2.18 on 2023-04-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_station', models.CharField(help_text='Station ID.', max_length=40)),
                ('record_date', models.DateField(help_text='Record date.', verbose_name='Record date.')),
                ('max_temp', models.FloatField(help_text='Max temp (in 0.1°C).')),
                ('min_temp', models.FloatField(help_text='Min temp (in 0.1°C).')),
                ('precip', models.FloatField(help_text='Precipitation (in 0.1mm).')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on.')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last updated.')),
            ],
            options={
                'ordering': ['weather_station'],
            },
        ),
        migrations.CreateModel(
            name='WeatherStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_station', models.CharField(help_text='Station ID.', max_length=40)),
                ('year', models.IntegerField(help_text='Stats done this year.')),
                ('max_temp_avg', models.FloatField(help_text='Avg max temp (in °C).', null=True)),
                ('min_temp_avg', models.FloatField(help_text='Avg min temp (in °C).', null=True)),
                ('total_precip', models.FloatField(help_text='Total precip (in cm).', null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on.')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last updated.')),
            ],
            options={
                'ordering': ['weather_station', 'year'],
            },
        ),
        migrations.AddConstraint(
            model_name='weatherstats',
            constraint=models.UniqueConstraint(fields=('weather_station', 'year'), name='Valid Stats by station, record and weather details.'),
        ),
        migrations.AddConstraint(
            model_name='weatherdetails',
            constraint=models.UniqueConstraint(fields=('weather_station', 'record_date', 'max_temp', 'min_temp', 'precip'), name='Valid record by station, record and weather details.'),
        ),
    ]
